### ISSUE TITLE
crontab的时间设置有问题

### ISSUE THREAD

**Issue by notaganin** [seal0207/EasyRealM#3]
例如`* */1 * * * systemctl restart realm`表示的是每个小时的每一分钟重启一次，而非每个小时重启一次，应该将第一个星号固定为一个值，例如`3 */1 * * *`，这样才能每个小时重启一次，天数也有这个问题。解决方法可以参照[https://crontab.guru/examples.html](https://crontab.guru/examples.html)

**Comment by seal0207** [comment]
OK，感谢指正，空了去改下
