### ISSUE TITLE
好像最近更新的这一版在centos7上运行不了

### ISSUE THREAD

**Issue by NP-Prob** [seal0207/EasyRealM#6]
如图所示：
![image](https://user-images.githubusercontent.com/9911456/116710302-2dce0680-aa04-11eb-9279-be1cdd6cd5cb.png)

**Comment by seal0207** [comment]
去/etc/systemd/system目录下看看内容是不是：
`
[Unit]
Description=realm
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
LimitNOFILE=32767
Type=simple
User=root
Restart=on-failure
RestartSec=5s
DynamicUser=true
ExecStart=/etc/realm/realm -c /etc/realm/config.json

[Install]
WantedBy=multi-user.target
`

**Comment by NP-Prob** [comment]
> 去/etc/systemd/system目录下看看内容是不是：
> `
> [Unit]
> Description=realm
> After=network-online.target
> Wants=network-online.target systemd-networkd-wait-online.service
> 
> [Service]
> LimitNOFILE=32767
> Type=simple
> User=root
> Restart=on-failure
> RestartSec=5s
> DynamicUser=true
> ExecStart=/etc/realm/realm -c /etc/realm/config.json
> 
> [Install]
> WantedBy=multi-user.target
> `

我查看了一下，确实是这个内容。

**Comment by NP-Prob** [comment]
> 去/etc/systemd/system目录下看看内容是不是：
> `
> [Unit]
> Description=realm
> After=network-online.target
> Wants=network-online.target systemd-networkd-wait-online.service
> 
> [Service]
> LimitNOFILE=32767
> Type=simple
> User=root
> Restart=on-failure
> RestartSec=5s
> DynamicUser=true
> ExecStart=/etc/realm/realm -c /etc/realm/config.json
> 
> [Install]
> WantedBy=multi-user.target
> `

前几天没时间，现在来填一下坑，防止后面还有同学遇到类似的问题。
刚仔细检查了一下，是这个问题：
/lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./realm)

可以通过如下方式解决：
`curl -O http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz`
`tar zxf glibc-2.18.tar.gz `
`cd glibc-2.18/`
`mkdir build`
`cd build/`
`../configure --prefix=/usr`
`make -j2`
`make install`
参见：[https://www.jianshu.com/p/92c7a042d8ba](url)
